### ISSUE TITLE
Discrepancy between Forward resolution and reverse lookup of ENS Names

### ISSUE THREAD

**Issue by manosamy** [ensdomains/ens#254]
ENS Nameowner can arbitrarily designate any wallet to be the resolving address by calling resolver.setAddr
However, reverse lookup can only be claimed by ENS NameOwner, so the modularity of choosing a resolver address who is different from Name owner is wasted.

Here is a scenario:
I own a name, and I resolve it to a smart contract that I deploy.
But I cant setup the reverse address mapping unless I transfer the name ownership to that contract first, and unless that contract is already built with a claim method (and a method to transfer the ownership back to me when its time for it to die).

**Comment by Arachnid** [comment]
There's some inevitable asymmetry between forward and reverse resolution, but I don't understand what your concern is here specifically.

**Comment by mcdee** [comment]
I extend the contract at https://github.com/wealdtech/wealdtech-solidity/blob/master/contracts/ens/ENSReverseRegister.sol to set up the reverse resolution at time of contract deploy.

**Comment by eepstein** [comment]
> There's some inevitable asymmetry between forward and reverse resolution, but I don't understand what your concern is here specifically.

I think the issue is this, assuming the "somecontract.eth" name has been registered and resolves to a valid contract address, then...

When I type in "somecontract.eth" as an address in Etherscan I get the page with the corresponding contract and information.

But, when I enter that contract address and try to do a reverse lookup ... crickets.  There's no way to, as an owner/deployer of a contract to specify its reverse name - the contract itself has to be able to do that.   Pretty inconvenient.

**Comment by Arachnid** [comment]
@eepstein There's not really a lot we can do about that. For security, only the address can claim its reverse name; if they don't, we can't display it.
